### ISSUE TITLE
Jessica's issue about FR>1

### ISSUE THREAD

**Issue by Penn-EDS** [Penn-EDS/Two-Channel-Drug-Delivery-controller-mice#5]
This one took forever to double check. For example, right now when the FR is set to 6 it only takes 5 wheel spins to get a puff. At first I thought it was only a file writing issue but it is definitely a wheel spinning issue. FR1 seems to work fine, but at FR2 it only requires 1, FR3 requires 2 etc.

**Comment by asantoslozada** [comment]
like this for FR4:
 
  49998 R 1
  59998 R 1
  69998 R 1
  79998 R 1  //this one is the spin 4
  79998 P 1 
 
And like this for FR1:
 
  79998 R 1  //this is the spin 1
  79998 P 1

Need to print all the R. The If need to be deleted.

**Comment by asantoslozada** [comment]
To Jessica

 49998 R 1
  59998 R 1
  69998 R 1
  79998 R 1  //this one is the spin 4
  79998 P 1 
 
And like this for FR1:
 
  79998 R 1  //this is the spin 1
  79998 P 1

The RED timestamp is not going to print the same value all the time. Sometimes the P is 1 millisecond more than the last R. That is happening because the time that the code takes between printing the last spin and the P is less than 0.5 milliseconds. So, when the number is 79998.4 the MCU is rounds it to 79998 and when is 79998.5 or more than .5 is rounds it up to 79999. If you are wondering if it is possible to print decimal, the answer is not. Let me know If you would like to be more accurate(equal) than that or if you are ok with that difference of +1 millisecond. 

ANSWER from Jessica:

I think that level of precision is fine and probably a better representation of what the animal is experiencing anyway. If we're ever at the point where we're concerned about sub-millisecond fluctuations between wheel spins and puffs we will be in fantastic shape and doing extremely cool/ fancy stuff (and will probably need significantly more expensive equipment). (Something to look forward to!)

Jessica

**Comment by asantoslozada** [comment]
Issue solved and closed
